/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ExampleDashboardRouteImport } from './routes/example-dashboard'
import { Route as ConstructsRouteImport } from './routes/constructs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConstructsNewRouteImport } from './routes/constructs/new'
import { Route as ConstructsListRouteImport } from './routes/constructs/list'

const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleDashboardRoute = ExampleDashboardRouteImport.update({
  id: '/example-dashboard',
  path: '/example-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructsRoute = ConstructsRouteImport.update({
  id: '/constructs',
  path: '/constructs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructsNewRoute = ConstructsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConstructsRoute,
} as any)
const ConstructsListRoute = ConstructsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ConstructsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/constructs': typeof ConstructsRouteWithChildren
  '/example-dashboard': typeof ExampleDashboardRoute
  '/templates': typeof TemplatesRoute
  '/test-error': typeof TestErrorRoute
  '/constructs/list': typeof ConstructsListRoute
  '/constructs/new': typeof ConstructsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/constructs': typeof ConstructsRouteWithChildren
  '/example-dashboard': typeof ExampleDashboardRoute
  '/templates': typeof TemplatesRoute
  '/test-error': typeof TestErrorRoute
  '/constructs/list': typeof ConstructsListRoute
  '/constructs/new': typeof ConstructsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/constructs': typeof ConstructsRouteWithChildren
  '/example-dashboard': typeof ExampleDashboardRoute
  '/templates': typeof TemplatesRoute
  '/test-error': typeof TestErrorRoute
  '/constructs/list': typeof ConstructsListRoute
  '/constructs/new': typeof ConstructsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/constructs'
    | '/example-dashboard'
    | '/templates'
    | '/test-error'
    | '/constructs/list'
    | '/constructs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/constructs'
    | '/example-dashboard'
    | '/templates'
    | '/test-error'
    | '/constructs/list'
    | '/constructs/new'
  id:
    | '__root__'
    | '/'
    | '/constructs'
    | '/example-dashboard'
    | '/templates'
    | '/test-error'
    | '/constructs/list'
    | '/constructs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructsRoute: typeof ConstructsRouteWithChildren
  ExampleDashboardRoute: typeof ExampleDashboardRoute
  TemplatesRoute: typeof TemplatesRoute
  TestErrorRoute: typeof TestErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example-dashboard': {
      id: '/example-dashboard'
      path: '/example-dashboard'
      fullPath: '/example-dashboard'
      preLoaderRoute: typeof ExampleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructs': {
      id: '/constructs'
      path: '/constructs'
      fullPath: '/constructs'
      preLoaderRoute: typeof ConstructsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructs/new': {
      id: '/constructs/new'
      path: '/new'
      fullPath: '/constructs/new'
      preLoaderRoute: typeof ConstructsNewRouteImport
      parentRoute: typeof ConstructsRoute
    }
    '/constructs/list': {
      id: '/constructs/list'
      path: '/list'
      fullPath: '/constructs/list'
      preLoaderRoute: typeof ConstructsListRouteImport
      parentRoute: typeof ConstructsRoute
    }
  }
}

interface ConstructsRouteChildren {
  ConstructsListRoute: typeof ConstructsListRoute
  ConstructsNewRoute: typeof ConstructsNewRoute
}

const ConstructsRouteChildren: ConstructsRouteChildren = {
  ConstructsListRoute: ConstructsListRoute,
  ConstructsNewRoute: ConstructsNewRoute,
}

const ConstructsRouteWithChildren = ConstructsRoute._addFileChildren(
  ConstructsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructsRoute: ConstructsRouteWithChildren,
  ExampleDashboardRoute: ExampleDashboardRoute,
  TemplatesRoute: TemplatesRoute,
  TestErrorRoute: TestErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
