export const IPC_CHANNELS = {
  getRuntimeInfo: "hive.desktop.getRuntimeInfo",
  notify: "hive.desktop.notify",
  openExternal: "hive.desktop.openExternal",
  viewerActivateServiceTab: "hive.desktop.viewer.activateServiceTab",
  viewerGetState: "hive.desktop.viewer.getState",
  viewerGoBack: "hive.desktop.viewer.goBack",
  viewerGoForward: "hive.desktop.viewer.goForward",
  viewerHide: "hive.desktop.viewer.hide",
  viewerNavigate: "hive.desktop.viewer.navigate",
  viewerOpenExternal: "hive.desktop.viewer.openExternal",
  viewerResetActiveTab: "hive.desktop.viewer.resetActiveTab",
  viewerReload: "hive.desktop.viewer.reload",
  viewerSetBounds: "hive.desktop.viewer.setBounds",
  viewerShow: "hive.desktop.viewer.show",
  viewerSyncServiceTabs: "hive.desktop.viewer.syncServiceTabs",
  viewerStateChanged: "hive.desktop.viewer.stateChanged",
} as const;
