export const HIVE_EMBEDDED_BROWSER_SAFE_KEYBINDS: Record<string, string> = {
  leader: "ctrl+x",
  "app.exit": "<leader>q",
  "command.palette.show": "<leader>p",
  "session.toggle.thinking": "<leader>i",
  "input.delete": "delete,shift+delete",
  "input.delete.line": "alt+shift+d",
  "input.delete.to.line.end": "alt+k",
  "input.delete.to.line.start": "alt+u",
  "input.delete.word.backward": "ctrl+backspace,alt+backspace",
  "input.line.end": "end",
  "input.line.home": "home",
  "input.move.left": "left",
  "input.move.right": "right",
  "input.newline": "shift+return,alt+return,ctrl+return",
  "input.select.line.end": "shift+end",
  "input.select.line.home": "shift+home",
  "input.undo": "super+z,alt+z",
  "input.word.backward": "ctrl+left,alt+b",
  "input.word.forward": "ctrl+right,alt+f",
  "model.dialog.favorite": "<leader>o",
  "model.dialog.provider": "<leader>z",
  "session.delete": "<leader>d",
  "session.rename": "<leader>k",
  "stash.delete": "<leader>d",
  "theme.switch": "<leader>j",
  "variant.cycle": "<leader>t",
};
