/**
 * Hive OpenCode Plugin Source
 *
 * This module provides the source code for the Hive OpenCode plugin written
 * to each cell worktree. The implementation
 * is in ./tools/hive.ts, which is type-checked during development and embedded
 * in compiled releases by Bun.
 */
import { constants, readFileSync, type Stats } from "node:fs";
import { lstat, mkdir, open, realpath, rename, unlink } from "node:fs/promises";
import { isAbsolute, join, relative, sep } from "node:path";
import hiveToolTypeScriptSource from "./tools/hive.ts" with { type: "text" };

/**
 * The source code for the Hive OpenCode plugin.
 * This is written to .opencode/plugins/hive/index.js in each cell worktree.
 */
const HIVE_PLUGIN_ID = "hive.cell.v2.r1.tools-context-shell-permission";
const HIVE_PLUGIN_OWNERSHIP_MARKER = `// @generated by Hive; managed plugin: ${HIVE_PLUGIN_ID}`;
const transpiledHiveToolSource = new Bun.Transpiler({
  loader: "ts",
  target: "bun",
}).transformSync(
  typeof hiveToolTypeScriptSource === "string"
    ? hiveToolTypeScriptSource
    : readFileSync(new URL("./tools/hive.ts", import.meta.url), "utf8")
);
const HIVE_TOOL_SOURCE = `${HIVE_PLUGIN_OWNERSHIP_MARKER}\n${transpiledHiveToolSource}`;
const PRIVATE_FILE_MODE = 0o600;
const FILE_MODE_BOUNDARY = 0o1000;
const LEGACY_HIVE_PLUGIN_SIGNATURES = [
  'import { createHash } from "node:crypto";',
  `HIVE_PLUGIN_ID = "${HIVE_PLUGIN_ID}"`,
  "export default Plugin.define({",
] as const;

function formatHiveServerHostname(hostname: string): string {
  if (hostname === "0.0.0.0") {
    return "127.0.0.1";
  }
  if (hostname === "::") {
    return "[::1]";
  }
  return hostname.includes(":") ? `[${hostname}]` : hostname;
}

export function resolveHiveServerUrl(): string {
  if (process.env.HIVE_URL) {
    return process.env.HIVE_URL;
  }

  const port = process.env.PORT ?? "3000";
  const configuredHostname =
    process.env.HOST ?? process.env.HOSTNAME ?? "127.0.0.1";
  const hostname = formatHiveServerHostname(configuredHostname);
  const protocol = process.env.HIVE_PROTOCOL ?? "http";

  return `${protocol}://${hostname}:${port}`;
}

export async function ensureHiveOpencodePlugin(
  worktreePath: string
): Promise<void> {
  const canonicalWorktree = await realpath(worktreePath);
  const opencodeDirectory = join(worktreePath, ".opencode");
  const pluginDirectory = join(opencodeDirectory, "plugins");
  const hivePluginDirectory = join(pluginDirectory, "hive");
  await ensureContainedDirectory(opencodeDirectory, canonicalWorktree);
  await ensureContainedDirectory(pluginDirectory, canonicalWorktree);
  await ensureContainedDirectory(hivePluginDirectory, canonicalWorktree);

  const pluginPath = join(hivePluginDirectory, "index.js");
  const existingPlugin = await lstatIfExists(pluginPath);
  if (existingPlugin?.isSymbolicLink()) {
    throw new Error(
      `Refusing to write Hive plugin through symlink: ${pluginPath}`
    );
  }
  if (existingPlugin) {
    const existingSource = await readExistingRegularFile(
      pluginPath,
      existingPlugin
    );
    if (!isHiveManagedPlugin(existingSource)) {
      throw new Error(
        `Refusing to overwrite workspace-owned Hive plugin: ${pluginPath}`
      );
    }
  }

  await writeManagedFileAtomically(pluginPath, HIVE_TOOL_SOURCE);
}

function isHiveManagedPlugin(source: string): boolean {
  return (
    source.startsWith(HIVE_PLUGIN_OWNERSHIP_MARKER) ||
    LEGACY_HIVE_PLUGIN_SIGNATURES.every((signature) =>
      source.includes(signature)
    )
  );
}

async function ensureContainedDirectory(
  directory: string,
  canonicalWorktree: string
): Promise<void> {
  await mkdir(directory).catch((error: unknown) => {
    if (!isExistingPathError(error)) {
      throw error;
    }
  });
  const stats = await lstat(directory);
  if (stats.isSymbolicLink() || !stats.isDirectory()) {
    throw new Error(
      `Refusing to use unsafe Hive-managed directory: ${directory}`
    );
  }
  const canonicalDirectory = await realpath(directory);
  if (!isWithin(canonicalWorktree, canonicalDirectory)) {
    throw new Error(`Hive plugin directory escapes worktree: ${directory}`);
  }
}

function isWithin(root: string, target: string): boolean {
  const path = relative(root, target);
  return (
    path === "" ||
    (!isAbsolute(path) && path !== ".." && !path.startsWith(`..${sep}`))
  );
}

function isMissingPathError(error: unknown): boolean {
  return (error as NodeJS.ErrnoException | undefined)?.code === "ENOENT";
}

function isExistingPathError(error: unknown): boolean {
  return (error as NodeJS.ErrnoException | undefined)?.code === "EEXIST";
}

function lstatIfExists(path: string) {
  return lstat(path).catch((error: unknown) => {
    if (isMissingPathError(error)) {
      return null;
    }
    throw error;
  });
}

async function readExistingRegularFile(
  path: string,
  initialStats: Stats
): Promise<string> {
  if (!initialStats.isFile()) {
    throw new Error(`Refusing to overwrite non-regular Hive plugin: ${path}`);
  }

  const handle = await open(
    path,
    constants.O_RDONLY + constants.O_NOFOLLOW + constants.O_NONBLOCK
  );
  try {
    const openedStats = await handle.stat();
    if (
      !openedStats.isFile() ||
      openedStats.dev !== initialStats.dev ||
      openedStats.ino !== initialStats.ino
    ) {
      throw new Error(`Hive plugin changed while checking ownership: ${path}`);
    }
    return await handle.readFile("utf8");
  } finally {
    await handle.close();
  }
}

/**
 * Configuration written to .hive/config.json in each cell worktree.
 * The plugin reads this to get the cell ID and Hive server URL.
 */
type HiveToolConfig = {
  cellId: string;
  hiveUrl: string;
};

/**
 * Generate the config.json content for a cell worktree.
 */
function generateHiveToolConfig(config: HiveToolConfig): string {
  return JSON.stringify(config, null, 2);
}

export async function ensureHiveToolConfig(
  worktreePath: string,
  config: HiveToolConfig
): Promise<void> {
  const canonicalWorktree = await realpath(worktreePath);
  const hiveDirectory = join(worktreePath, ".hive");
  await ensureContainedDirectory(hiveDirectory, canonicalWorktree);

  const configPath = join(hiveDirectory, "config.json");
  const existingConfig = await lstatIfExists(configPath);
  if (existingConfig?.isSymbolicLink()) {
    throw new Error(
      `Refusing to write Hive config through symlink: ${configPath}`
    );
  }

  await writeManagedFileAtomically(configPath, generateHiveToolConfig(config));
}

async function writeManagedFileAtomically(
  destination: string,
  content: string
): Promise<void> {
  if (await managedFileMatches(destination, content)) {
    return;
  }

  const temporaryPath = `${destination}.${process.pid}.${crypto.randomUUID()}.tmp`;
  const openFlags =
    constants.O_WRONLY +
    constants.O_CREAT +
    constants.O_EXCL +
    constants.O_NOFOLLOW;
  try {
    const handle = await open(temporaryPath, openFlags, PRIVATE_FILE_MODE);
    try {
      await handle.writeFile(content, "utf8");
      await handle.sync();
    } finally {
      await handle.close();
    }
    await rename(temporaryPath, destination);
  } catch (error) {
    await unlink(temporaryPath).catch(() => null);
    throw error;
  }
}

async function managedFileMatches(
  destination: string,
  content: string
): Promise<boolean> {
  const destinationStats = await lstatIfExists(destination);
  if (!(destinationStats && isPrivateRegularFile(destinationStats))) {
    return false;
  }

  let handle: Awaited<ReturnType<typeof open>> | undefined;
  try {
    handle = await open(
      destination,
      constants.O_RDONLY + constants.O_NOFOLLOW + constants.O_NONBLOCK
    );
    const openedStats = await handle.stat();
    if (
      openedStats.dev !== destinationStats.dev ||
      openedStats.ino !== destinationStats.ino ||
      !isPrivateRegularFile(openedStats)
    ) {
      return false;
    }
    return (await handle.readFile("utf8")) === content;
  } catch (error) {
    if (isMissingPathError(error)) {
      return false;
    }
    throw error;
  } finally {
    await handle?.close();
  }
}

function isPrivateRegularFile(stats: Stats): boolean {
  const currentUserId =
    typeof process.getuid === "function" ? process.getuid() : undefined;
  const permissionsArePrivate =
    process.platform === "win32" ||
    stats.mode % FILE_MODE_BOUNDARY === PRIVATE_FILE_MODE;
  return (
    stats.isFile() &&
    stats.nlink === 1 &&
    permissionsArePrivate &&
    (currentUserId === undefined || stats.uid === currentUserId)
  );
}
