name: Setup Desktop CI Environment
description: Shared setup for desktop installer and WebDriver jobs

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "22.12.0"
  bun-version:
    description: Bun version
    required: false
    default: "1.3.5"
  install-webdriver-deps:
    description: Install Linux WebDriver/Xvfb packages
    required: false
    default: "false"
  install-opencode:
    description: Install OpenCode CLI and add to PATH
    required: false
    default: "false"
  install-tauri-driver:
    description: Install tauri-driver and add cargo bin to PATH
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Bun download artifacts
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: bun-cache-${{ runner.os }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          bun-cache-${{ runner.os }}-

    - name: Cache Cargo registry and git index
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-cache-${{ runner.os }}-${{ hashFiles('src-tauri/Cargo.lock') }}
        restore-keys: |
          cargo-cache-${{ runner.os }}-

    - name: Cache Tauri build artifacts
      uses: actions/cache@v4
      with:
        path: src-tauri/target
        key: tauri-target-${{ runner.os }}-${{ hashFiles('src-tauri/Cargo.lock', 'src-tauri/Cargo.toml', 'src-tauri/build.rs', 'src-tauri/tauri.conf.json') }}
        restore-keys: |
          tauri-target-${{ runner.os }}-

    - name: Cache OpenCode CLI
      if: ${{ inputs.install-opencode == 'true' }}
      id: opencode-cache
      uses: actions/cache@v4
      with:
        path: ~/.opencode/bin
        key: opencode-${{ runner.os }}-1

    - name: Install Linux desktop dependencies
      shell: bash
      run: |
        extra_packages=""
        if [ "${{ inputs.install-webdriver-deps }}" = "true" ]; then
          extra_packages="webkit2gtk-driver xvfb"
        fi

        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libxdo-dev \
          libssl-dev \
          patchelf \
          $extra_packages

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install OpenCode CLI
      if: ${{ inputs.install-opencode == 'true' && steps.opencode-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: curl -fsSL https://opencode.ai/install | bash -s -- --no-modify-path

    - name: Add OpenCode CLI to PATH
      if: ${{ inputs.install-opencode == 'true' }}
      shell: bash
      run: echo "$HOME/.opencode/bin" >> "$GITHUB_PATH"

    - name: Install tauri-driver
      if: ${{ inputs.install-tauri-driver == 'true' }}
      shell: bash
      run: cargo install tauri-driver --locked

    - name: Add Cargo binaries to PATH
      if: ${{ inputs.install-tauri-driver == 'true' }}
      shell: bash
      run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
