name: Setup Desktop CI Environment
description: Shared setup for desktop installer and Electron jobs

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "22.12.0"
  bun-version:
    description: Bun version
    required: false
    default: "1.3.5"
  install-opencode:
    description: Install OpenCode CLI and add to PATH
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun download artifacts
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: bun-cache-${{ runner.os }}-${{ hashFiles('bun.lock') }}
        restore-keys: |
          bun-cache-${{ runner.os }}-

    - name: Cache OpenCode CLI
      if: ${{ inputs.install-opencode == 'true' }}
      id: opencode-cache
      uses: actions/cache@v4
      with:
        path: ~/.opencode/bin
        key: opencode-${{ runner.os }}-1

    - name: Install Linux desktop dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          libnss3 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libasound2

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install OpenCode CLI
      if: ${{ inputs.install-opencode == 'true' && steps.opencode-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: curl -fsSL https://opencode.ai/install | bash -s -- --no-modify-path

    - name: Add OpenCode CLI to PATH
      if: ${{ inputs.install-opencode == 'true' }}
      shell: bash
      run: echo "$HOME/.opencode/bin" >> "$GITHUB_PATH"
