import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const sourcePath = resolve(
  process.cwd(),
  "apps/server/src/agents/tools/hive.ts"
);
const outputPath = resolve(
  process.cwd(),
  "apps/server/src/agents/hive-opencode-tool-source.generated.ts"
);

const source = await readFile(sourcePath, "utf8");
const encoded = Buffer.from(source, "utf8").toString("base64");
const chunkSize = 120;
const chunks = encoded.match(new RegExp(`.{1,${chunkSize}}`, "g")) ?? [];
const chunkLines = chunks.map((chunk) => `  "${chunk}",`).join("\n");

const nextContent = `/**\n * Auto-generated by scripts/dev/generate-hive-opencode-tool-source.ts\n * Do not edit directly.\n */\nexport const HIVE_TOOL_SOURCE_EMBEDDED_BASE64 = [\n${chunkLines}\n].join("");\n`;

const prevContent = await readFile(outputPath, "utf8").catch(() => null);

if (prevContent !== nextContent) {
  await writeFile(outputPath, nextContent, "utf8");
  console.log(`Generated ${outputPath} from ${sourcePath}`);
} else {
  console.log(`${outputPath} already up to date`);
}
